version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # 使用Java 8环境的Docker镜像
    steps:
      - checkout  # 检出代码
      - run: mvn install  # 运行mvn install命令来打包

      # 将打包结果推送到release分支下日期.jar
      - run:
          name: Copy JAR to release branch
          command: |
            mkdir -p release
            date=$(date +%Y%m%d)  # 获取当前日期，格式：年月日
            cp target/*.jar release/${date}.jar

      # 推送代码变更到release分支
      - run:
          name: Commit and push changes
          command: |
            git config --global user.email "circleci@example.com"
            git config --global user.name "CircleCI"
            git add release/*
            git commit -m "Auto-push release JAR [skip ci]"
            git push origin HEAD:release
