version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # 使用Java 8的Docker镜像

    steps:
      - checkout  # 检出代码

      - run:
          name: Build and package
          command: mvn clean install  # 执行Maven的clean和install命令
          command: ls

      - store_artifacts:  # 将target目录作为产物保存
          path: /target  # 修改为您的项目中target目录的路径

workflows:
  version: 2
  build:
    jobs:
      - build
