version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/windows@windows-2019

    steps:
      - checkout

      # 安装JDK 8
      - run:
          name: Install JDK 8
          command: |
            choco install openjdk8 --version 8.292.10
            refreshenv

      # 运行 Maven install 命令
      - run:
          name: Build and package
          command: mvn install

      # 推送打包结果到 release 分支下
      - run:
          name: Push to release branch
          command: |
            # 替换下面的 <日期> 为当前日期，例如 20230804
            $date = Get-Date -Format "yyyyMMdd"
            $jarFileName = "target\your_artifact.jar"
            $targetBranch = "release"
            git checkout -b $targetBranch
            git add $jarFileName
            git commit -m "Adding build for $date"
            git push origin $targetBranch
